spring.application.name=AcademiaElSoto
spring.mustache.suffix=.html

# Si no hay variable DB_URL en .env usa localhost: .....
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/academia_elsoto?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}

# Si no hay variable DB_USER, usa root
spring.datasource.username=${DB_USER:root}

#Si no existe la variable DB_PASS, la aplicación dará error
spring.datasource.password=${DB_PASS}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8443
server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=selfsigned

server.ssl.key-store-password=${SSL_PASSWORD}


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.springframework.security=DEBUG