package es.codeurjc.AcademiaElSoto.security;

import org.springframework.context.annotation.Configuration;
import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.web.servlet.HandlerInterceptor;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.config.annotation.InterceptorRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * Configuration class to handle CSRF token injection into the web UI.
 * This mitigates A05:2025 - Injection (Cross-Site Request Forgery).
 */
@Configuration
public class CSRFHandlerConfiguration implements WebMvcConfigurer {

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        // Registering the interceptor to apply to all web controllers
        registry.addInterceptor(new CSRFHandlerInterceptor());
    }
}

/**
 * Interceptor that extracts the CSRF token from the session and adds it to the 
 * ModelAndView, making it available in Mustache templates via the {{token}} variable.
 */
class CSRFHandlerInterceptor implements HandlerInterceptor {

    @Override
    public void postHandle(final HttpServletRequest request, final HttpServletResponse response, final Object handler,
            final ModelAndView modelAndView) throws Exception {

        if (modelAndView != null) {
            // Retrieve the synchronizer token generated by Spring Security
            CsrfToken token = (CsrfToken) request.getAttribute("_csrf");
            if (token != null) {
                // The token is added to the model to be included in state-changing forms (POST)
                modelAndView.addObject("token", token.getToken());
            }
        }
    }
}